### PR TITLE
GitHub actions improvements

### PR DESCRIPTION
**Pull request by jwimberl**
This PR modifies test.yml by replacing the xenial and CentOS 7 based SciDB 19.11 CE target images with the CentOS 7-only EE target images, which include SciDB versions 19.11 and 22.5. Additionally, a second version of the test is added for Rocky 8 based target images, principally for SciDB 23.2, which runs the unit test twice using both the shim and httpapi ports.

In both cases, the matrix of SciDB versions and R versions for which the tests run are changed from hard-coded settings to GitHub repository variables (SCIDB_VER_LIST_CENTOS, SCIDB_VER_LIST_ROCKY, and R_VER_LIST).

### CODE REVIEW

**Comment by jwimberl** [comment]
Two comments regarding readiness of this branch for merger:
* The Rocky test runs the unit test file a.R twice, the second time setting SCIDB_HTTP_PORT to 8239. Depending upon the order in which this branch and the httpapi branch are merged, this test may not initially pass. It should, though, pass when both are merged in, as demonstrated by this test run in a branch merging the two:  https://github.com/Paradigm4/SciDBR/actions/runs/4766242602
* Some settings in the Rocky 8 workflow script may be provisional and require changing tracking SciDB 23.2 development, in particular the logic setting the SCIDB_PATH to `/opt/scidb/22.6` rather than `/opt/scidb/23.2`

**Review by ksens — CHANGES_REQUESTED** [review]
@jwimberl 
LGTM -- excellent work. One minor change came to mind:

- To be more explicit, how about we change the name for `test.yml` to `test-centos7.yml`?

In terms of deployment logistics, I propose that we plan the merge in this fashion:

- merge `httpapi` #277 into master first (will need a bit more testing across apps... Over next week, let us discuss within the CS group and finalize an internal deadline for this merge)
- then merge this PR into master

**Review by rvernica — COMMENTED** [review]
Looks good to me. I guess you have a typo in the PR description:
_with the CentOS 7-only CE target images_ -> _CE_ should be _EE_

**Comment by rvernica** [comment]
Also, the Rocky 8 setup seems to fail

**Comment by jwimberl** [comment]
> * To be more explicit, how about we change the name for `test.yml` to `test-centos7.yml`?

Agreed

> _with the CentOS 7-only CE target images_ -> _CE_ should be _EE_

I will fix this as well

> Also, the Rocky 8 setup seems to fail

See the first comment on the PR -- this is because it includes a test using the httpapi port but this branch is not forked of the httpapi branch. I ran a test (linked above) that shows that it passes when both branches are merged.

**Comment by jwimberl** [comment]
Closing this PR in favor of #287 , so that both the httpapi functionality and the httpapi unit test support via GitHub actions will be unified into a single PR into master (#277)

**Pull request closed without merging**
