### PR TITLE
R expression parsing

### PR DESCRIPTION
**Pull request by jwimberl**
Add classes, utilities, and methods to assist users in creating AFL expressions, in particular for filter operations, from expressions written in R syntax.

### CODE REVIEW

**Comment by jwimberl** [comment]
I've added several things to this pull request:

 * turning the unit test framework into `testthat` tests, adding one for the AFL expression parsing
 * splitting the monolithic pkgdown documentation [page](folder: docs) into several vignettes, including new documentation for the AFL expression parsing from this branch
 * Adding a deploy-docs workflow that generates the pkgdown documentation and pushes it to the gh-pages branch upon any tag. This has been manually tested using a test tag (the production gh-pages is currently being served from a branch "gh-pages-old" forked from the old gh-pages).

**Comment by ksens** [comment]
@smoore-p4 @rls-p4 

Can you have a look at this PR. We ideally want to merge this this week, and also before #277 . 

- @smoore-p4 - you would be the primary reviewer since similar functionality exists in ArrayOpR. Hopefully this can be the only place this functionality stays on in the future
- @rls-p4 - wanted your inputs since you have done a major rehaul of scidbR via #277 -- wanted to make sure this PR is consistent with that

**Review by ksens — CHANGES_REQUESTED** [review]
@jwimberl Please update NEWS.md with a summary of your changes

**Review by rls-p4 — COMMENTED** [review]
I see nothing here that would conflict with the SciDBR 4.0 changes in #277 . I can't comment on the rest of the content of this change, though.

**Review by smoore-p4 — COMMENTED** [review]
Looked over the tests for the R expression to AFL stuff, and it looks good. The one thing that the ArrayOp e_to_afl does that this doesn't is converting `if(a==2) x else y` to the AFL `iif(a = 2,x,y)`. However I'm not sure if that should end up in scidbr or not, since that isn't really used as a filter thing, but more in project/apply. (Mostly opening this up to discussion... I don't really have strong feelings either way, and can just keep that inside ArrayOp.) (See the link for the ArrayOp tests for that functionality.)
 https://github.com/Paradigm4/ArrayOpR/blob/f3e210b0293227edaba5f65c91d1095b21d7c82e/tests/testthat/test_e_to_afl.R#L11

**Comment by jwimberl** [comment]
Thanks @smoore-p4 -- I have plans to include support for conditionals by adding a general class to match N-ary calls. This could parse an R `ifelse(a == 2, x, y)` and map it to `iif(a = 2, x, y)` during the AFL buliding step; treating `if (a == 2) x else y` and  `if (a == 2) { x } else { y }` synonymously, while giving an error for `if (a == 2) { w; x } else { y; z }`, is easy (the former is parsed by rlang the same as the `ifelse` call, just with the call name itself different, and rlang parses `{ ... }` as a call with one argument for each newline or semicolon separated entry).

Those plans fell outside the scope for this PR for exactly the reason you said -- `iif` isn't needed in filter expressions that return booleans. However, just as scidb::filter is a thin wrapper around scidb::expression_parser, handling named key-value pairs in a special way, my thought was to eventually introduce a function with a name like scidb::assign that would reuse all the expression parsing code, but expect its entries to named key-value pairs, and which could be converted to AFL in slightly different ways depending on the context (e.g. with comma-separations in apply and `as` in aggregates)

**Comment by ksens** [comment]
LGTM

**Comment by rls-p4** [comment]
@jwimberl Can you also merge this change into the [httpapi](https://github.com/Paradigm4/SciDBR/tree/httpapi) branch?

**Comment by jwimberl** [comment]
> @jwimberl Can you also merge this change into the [httpapi](https://github.com/Paradigm4/SciDBR/tree/httpapi) branch?

Created #287

**Pull request merged**
