### PR TITLE
Update docs with keepalive options

### PR DESCRIPTION
**Pull request by ksens**
@rvernica 

I realized that docs need to be updated to reflect the `keepalive` options that are needed to resolve issues like https://github.com/Paradigm4/SciDBR/issues/253. 

- [ ] Can you update the scidbR docs that are hosted at https://paradigm4.github.io/SciDBR/ with the changes I put in the `Rmd` file. 
- [ ] At the same time, is it possible to have the docs be built automatically using GA? Or is that already the case?

### CODE REVIEW

**Review by rvernica — APPROVED** [review]
Looks good to me.

**Comment by rvernica** [comment]
For updating the docs,  the HTML files need to be generated and committed here https://github.com/Paradigm4/SciDBR/tree/gh-pages I don't think there is an automated process for this right now. We do the same in SciDB-Py. Automating this might be overkill if we don't updated the docs very often.

**Comment by ksens** [comment]
@rvernica Do you have a code snippet that I can run to build the HTML pages and update the `gh-pages` branch? If not, I can figure it out myself too.

**Comment by rvernica** [comment]
No, I do not, but I think you just need to knit this file https://github.com/Paradigm4/SciDBR/blob/master/vignettes/scidb.Rmd in HTML. I'm not sure how the other HTML files are generated but I don't think there are linked to the home page anyway.

**Pull request closed without merging**
