### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by dvg-p4**
Add `R6` to Imports; move `bit64` from Depends to Imports; replace undeclared `glue::glue()` usage with `paste()`/`paste0()`

(see https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-depends)

### CODE REVIEW

**Comment by agvandervelde** [comment]
does the rocky 8 build failure have to do with libpqxx being upgraded in the process?

**Review by jwimberl — APPROVED** [review]
LGTM

**Comment by dvg-p4** [comment]
Any idea what's up with that test failure?

**Review by mpeterson-p4 — APPROVED** [review]

**Comment by ksens** [comment]
@jwimberl 

Can you point out where R6 is used in scidbR?

**Comment by jwimberl** [comment]
> @jwimberl
> 
> Can you point out where R6 is used in scidbR?

Several R6 classes are used in expression parsing; c.f. https://github.com/Paradigm4/SciDBR/blob/master/R/afl.R#L155

**Review by ksens — CHANGES_REQUESTED** [review]
@dvg-p4 

Good catch. Minor edit -- can you update `NEWS.md` with a one-liner describing the changes.

**Review by ksens — APPROVED** [review]
LGTM

**Pull request merged**
