### PR TITLE
Transform $ for internal dims into X_ when "applying them out"

### PR DESCRIPTION
**Pull request by agvandervelde**
This fixes https://github.com/Paradigm4/SciDBR/issues/263 by transforming ^$... into X_...

@mpietras-p4 fyi

### CODE REVIEW

**Comment by ksens** [comment]
Question for @mpietras-p4 / @agvandervelde - Why is our application-level code invoking the `aio=FALSE` path? Shouldn't all downloads invoke the `aio=TRUE` path?

@agvandervelde - Would you be able to add a test for this to the scidbR test suite?

**Comment by agvandervelde** [comment]
Hi Kriti, sure, I'll add a test for this.

**Comment by agvandervelde** [comment]
@ksens I'm done with this; ready to merge when you are.

**Comment by ksens** [comment]
@agvandervelde 

LGTM - merging to master.

Great work fixing the issue and also improving the GA testing along the way. Glad that we now have a readable log of running `a.R`.

**Pull request merged**
