### PR TITLE
Merge v3.1.5 from master

### PR DESCRIPTION
**Pull request by rls-p4**

### CODE REVIEW

**Comment by ksens** [comment]
@rls-p4 

Can you resolve merge conflicts and merge this PR in. Thanks. 

We have started testing `httpapi` branch in single-cell... It would be good to keep `httpapi` branch updated with the latest bug-fixes in `master`.

**Comment by rls-p4** [comment]
@ksens does this PR only contain commits from master, or did you add more updates?

**Comment by ksens** [comment]
@rls-p4 

I did not make any changes on this PR. I only commented here because this seemed to have all the fixes from master. 

In fact, Github auto-suggested this PR when I was trying to compare `master` and `httpapi`.

**Comment by rls-p4** [comment]
@ksens The `httpapi` branch of SciDBR is now up to date with master.

**Pull request merged**
